ALTER TABLE public.quotes
  ADD COLUMN IF NOT EXISTS coverage_type TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS total_declared_value NUMERIC(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS coverage_cost NUMERIC(12,2) DEFAULT 0;